In [1]:
import pandas as pd
df=pd.read_csv("EVDATASET.csv")
df.head()

,Year,Country,Brand,Model,Battery_kWh,Range_km,Motor_Power_kW,Weight_kg,Price_USD,Charging_Stations,Sales,Govt_Incentive_USD
0,2016,China,Tata,Nexon EV,69.9,332,135,1789,33741,50789,1520,1200
1,2018,USA,Hyundai,Kona Electric,50.6,353,117,1509,36758,36337,1478,900
2,2022,India,Tata,Nexon EV,39.7,381,88,1387,26752,3473,1832,600
3,2019,Germany,Tesla,Model S,49.1,268,101,1367,65866,33699,1018,810
4,2024,Germany,Audi,e-tron,59.7,490,87,1793,54986,48335,3072,360

### ELECTRIC VEHICLE DATASET ANALYSIS
### OBJECTIVE 
To perform initial data loading and exploration on an electric vehicle dataset using python and pandas 
### STEPS PERFORMED
1. imported the pandas library
2. loaded the dataset(EVDATASET.csv)using pd.read_csv()
3. displayed the first few rows with df.read() to verify successful loading
### OBSERVATION
1. the dataset contains details like year , country,brand,model,battery(kwh),range(km),motor power,weight,price,charging stations,and sales.
   data appeared clean for further analysis